services:
  mongo:
    image: mongo:8
    container_name: url-mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    command: mongod --quiet --logpath /dev/null 

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: url-backend
    depends_on:
      - mongo
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/urlGlow
      - JWT_SECRET=super_secret_key
      - JWT_REFRESH_SECRET=super_refresh_secret_key
      - SALT_ROUNDS=10
    command: pnpm dev
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/pnpm-lock.yaml
          action: rebuild
        - path: ./backend/Dockerfile
          action: rebuild


volumes:
  mongo_data:
    driver: local